---

language: node_js

node_js:
  - node

script:
  - make lint
  - make test-coverage

env:
  global:
    - secure: "eoSvaGhzn7QAfZhwoPoCaxouGWB8nP0Pq1ST4iLMuzJ48w2bevgx8RN3ZI6uM9yKpyoieUtOQid7PnjP8mVTG/OZ5S6IdQHEXT3w5NLt/xQ+M/j7mbFm1zFNzOR5HcntFfCHsr/cQSmR+wBhMi43aKro0iK3oh00OqjjBUpFTs8eNa11bZGqTEu/xQlznyS70Y9TlmmmW70JJBLMm+Q0gCqg3Xw4VQFne7+mxsME1KMe417Py0yFMolz2kPWdYemFPuqUCH+8EocD+nW9nULDfIrR/MXKwodPgP/0n3QtNlKbTH56AQ8RsvTkPra5qM7SKUnZMPOs2jGnl8TSEtOKhlyw/lL67mH/G09rH2mwrkiB9py48dCWgOB4z3xyxuIOHz+I2ZGPRdMSLzXpuYRzzBt+A7c7QinJjyV9WNIetDnM62d16HOFV4akWFr1dXPOi22qboWsSdZtzT83mulT0kJ3LQeNn6UtX/7J4Jm5byzbM5NZ2daUqJDOfjKb2sOI0jz4rvfETrAuOp1JDzz3ka2YfWmWg2xCLG5Nq50dtfShzU8DkXN9T5PULr69Gdvp+jI0OP+lMZC7U8JTFirVhiD4EM0i2byYzgSHSwO8OpgBqH7tlTpNHMkcNpxpI1s6XG6Z6pFjnzwgq4SVf4xQO8/wJAF8QzmBcCBae/GmQE="

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
